### ISSUE TITLE
기둥 사이에 공간 있어요

### ISSUE THREAD

**Issue by JJuOn** [onetwothreeefour/ProjectMaze#1]
![image](https://user-images.githubusercontent.com/43328935/149339453-a77b8e5f-cfeb-4db8-8b19-b4efea52f106.png)

**Comment by Leekee0905** [comment]
![image](https://user-images.githubusercontent.com/59133563/149439799-7102302c-f157-492f-81d6-f35363b9b64d.png)

해결했습니다~ 감사합니다
